// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALSZ92G6sdeaylidr1Z65a6QbroZKMyDE',
    appId: '1:423719724937:web:ccc2b55b5e145c32552358',
    messagingSenderId: '423719724937',
    projectId: 'wowpress-beta',
    authDomain: 'wowpress-beta.firebaseapp.com',
    storageBucket: 'wowpress-beta.appspot.com',
    measurementId: 'G-Q3PBDRW224',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr2a5pUimvFqjnHKdiE-iWibh33MdKPpI',
    appId: '1:423719724937:android:0ccc2681d908ca48552358',
    messagingSenderId: '423719724937',
    projectId: 'wowpress-beta',
    storageBucket: 'wowpress-beta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8mbwIQl85ykLekFjfg1RT1ikIq-wpB6s',
    appId: '1:423719724937:ios:d9146305bcec0b6d552358',
    messagingSenderId: '423719724937',
    projectId: 'wowpress-beta',
    storageBucket: 'wowpress-beta.appspot.com',
    iosBundleId: 'com.example.flutterTut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8mbwIQl85ykLekFjfg1RT1ikIq-wpB6s',
    appId: '1:423719724937:ios:032a533c3ade3232552358',
    messagingSenderId: '423719724937',
    projectId: 'wowpress-beta',
    storageBucket: 'wowpress-beta.appspot.com',
    iosBundleId: 'com.example.flutterTut.RunnerTests',
  );
}
