// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for lin:ux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcWf7-fdnB2LdWBVMocLWsaeSIpA3NEiA',
    appId: '1:949694906192:web:c74d351b841e7e3fd53655',
    messagingSenderId: '949694906192',
    projectId: 'instragram-tutc',
    authDomain: 'instragram-tutc.firebaseapp.com',
    databaseURL: 'https://instragram-tutc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'instragram-tutc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUQazDrWwrNjG_TMh3JHMkJMmRjHQ7I9I',
    appId: '1:949694906192:android:b8b7a04d1013bd6ed53655',
    messagingSenderId: '949694906192',
    projectId: 'instragram-tutc',
    databaseURL: 'https://instragram-tutc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'instragram-tutc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHPw5aWgAQ4I83PIHV162V61W0miIMAjU',
    appId: '1:949694906192:ios:dba0d1797e8432b6d53655',
    messagingSenderId: '949694906192',
    projectId: 'instragram-tutc',
    databaseURL: 'https://instragram-tutc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'instragram-tutc.appspot.com',
    iosClientId: '949694906192-ognhs4q22lslc22gfeqopbnarve6t65d.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHPw5aWgAQ4I83PIHV162V61W0miIMAjU',
    appId: '1:949694906192:ios:84b3e964ec372e5dd53655',
    messagingSenderId: '949694906192',
    projectId: 'instragram-tutc',
    databaseURL: 'https://instragram-tutc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'instragram-tutc.appspot.com',
    iosClientId: '949694906192-p0v4sfh9i2ru8ocodc0hu0ti7c39ptlp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTut.RunnerTests',
  );
}
